version: "3.9"

services:
  redis:
    build:
      context: ..
      dockerfile: infra-local/Dockerfile.redis
    container_name: spotify-liker-redis
    ports:
      - "6379:6379"
    environment:
      # Optional: Allow Redis to run without a password for local testing
      ALLOW_EMPTY_PASSWORD: "yes"
