version: "3.9"

services:
  redis:
    image: redis:7
    container_name: spotify-liker-redis
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    command: ["redis-server", "--maxmemory-policy", "noeviction"]

  worker:
    build:
      context: ../
      dockerfile: infra-prod/Dockerfile
    container_name: spotify-liker-worker
    env_file:
      - ../.env.production
    command: ["bun", "background-worker/worker.ts"]